name: mc-tag
main: com.pooled.mctag.MCTag
version: 1.0
api-version: 1.18
commands:
  tag:
    description: Start the Tag game with a random or specified tagger.
    usage: /<command> [player]
    permission-message: You don't have permission.
